### ISSUE TITLE
Documentation to use it with HA ? Primary,Backup,Monitor node ? Should it require 3 exporter each for one node ? 

### ISSUE THREAD

**Issue by shukla2009** [solacecommunity/solace-prometheus-exporter#29]

**Comment by shukla2009** [comment]
I am using Solace Software Broker with HA and DR Site so in total running 6 nodes of Solace.
Main Site => Primary,Backup,Monitor[3]
Dr Site=> Primary,Backup,Monitor[3]

Any reference/document to monitor this kind of topology.

**Comment by GreenRover** [comment]
Here is what i would use:

Create a: https://github.com/solacecommunity/solace-prometheus-exporter/blob/master/docker/solace_prometheus_exporter.ini
and inject this via docker volume to /etc/solace_prometheus_exporter.ini

```ini
[endpoint.msg-broker-std]
Version=*|*
Health=*|*
Spool=*|*
Redundancy=*|*
ConfigSyncRouter=*|*
Vpn=*|*
VpnReplication=*|*
ConfigSyncVpn=*|*
Bridge=*|*
VpnSpool=*|*

[endpoint.msg-broker-stats]
VpnStats=*|*
BridgeStats=*|*

[endpoint.msg-broker-details]
ClientStats=*|*
QueueRates=*|*
QueueDetails=*|*

[endpoint.monitoring-broker]
Version=*|*
Health=*|*
Spool=*|*
Vpn=*|*
Bridge=*|*
VpnSpool=*|*
```
Here the Prometheus config.
- Here a guess you run the exporter along with the broker? 
- I in my case have a singe central exporter and inject username and pw with http post.
- This makes updates much easier, caused by the huge amount of broker we operate.

```
scrape_configs:
  - job_name: solace-msg-broker-std
    scrape_interval: 15s
    metrics_path: /msg-broker-std
    static_configs:
      - targets:
        - broker-main-a:9628
        - broker-main-b:9628
        - broker-dr-a:9628
        - broker-dr-b:9628
        
  - job_name: solace-msg-broker-stats
    scrape_interval: 5m
    metrics_path: /msg-broker-stats
    static_configs:
      - targets:
        - broker-main-a:9628
        - broker-main-b:9628
        - broker-dr-a:9628
        - broker-dr-b:9628
        
  - job_name: solace-msg-broker-details
    scrape_interval: 15m
    metrics_path: /msg-broker-details
    static_configs:
      - targets:
        - broker-main-a:9628
        - broker-main-b:9628
        - broker-dr-a:9628
        - broker-dr-b:9628

  - job_name: solace-mon-broker
    scrape_interval: 15s
    metrics_path: /monitoring-broker
    static_configs:
      - targets:
        - broker-main-mon:9628
        - broker-dr-mon:9628
```

Attention:
- If you expect more then 1000 queues per vpn
- If you expect more then 1000 connected msg clients
- solace-msg-broker-details: will harm your broker performance!
