### ISSUE TITLE
Looking to monitor Multiple brokers with centralised Exporter

### ISSUE THREAD

**Issue by dpkbhatt91** [solacecommunity/solace-prometheus-exporter#43]
Hi Team, 

I am looking to monitor multiple brokers and instead of grafana i am using New Relic for remote write and dont want to send any sensitive details such as userName and pwd to New Relic as its SaaS solution.

I have got some information from 
https://github.com/solacecommunity/solace-prometheus-exporter/issues/29

however, i am still bit confused on how do i pass username and pwd details if i dont add it in target format 

e,g.

- job_name: 'solace-std'
  scrape_interval: 15s
  metrics_path: /solace-std
  static_configs:
    - targets:
      - https://USER:PASSWORD@first-broker:943
      - https://USER:PASSWORD@second-broker:943
      - https://USER:PASSWORD@third-broker:943
 
and i tried this (Adding multiple brokers) however solace exporter still scraped from the scrape URI which i put in ini file.

**Comment by GreenRover** [comment]
My solution for this problem is:

Having a nginx reverse proxy in between:
 prometheus-exporter -> nginx -> prometheus

If you can not trust your prometheus / new relict, you can do it this way:

Example nginx config:
```
worker_processes 5;

error_log /dev/fd/2 info;

events {
    worker_connections 8192;
}

http {
    gzip on;

    proxy_cache_path /tmp/nginx_cache levels=1:2
                keys_zone=exporter_cache:10m
                max_size=10m
                inactive=20m
                use_temp_path=off;

    log_format tms-ssp   '$remote_addr - $remote_user [$time_local] '
                         '"$request" $status $body_bytes_sent $request_time '
                         '$upstream_cache_status $upstream_response_time '
                         '"$http_referer" "$http_user_agent"';

    access_log /dev/fd/1 tms-ssp flush=3s buffer=64k;

    server {
        listen 9000;
        
        proxy_cache_lock on;
        proxy_cache_lock on;
        proxy_cache_revalidate off;
        add_header X-Cache-Status $upstream_cache_status;
        proxy_ignore_headers Cache-Control;
        proxy_cache_valid any 5s;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_cache exporter_cache;

        location /nginx_status {
          stub_status;
        }

        location /tms/iad/iltisgateway/t-ltta/broker {
            proxy_method POST;
            proxy_pass http://solace-exporter:1920/solace?m.Version=*|*&m.Health=*|*&m.Spool=*|*&m.Redundancy=*|*&m.ConfigSyncRouter=*|*;
            proxy_cache_key "tms/iad/iltisgateway/t-ltta_mr-0yg8yf443f2.messaging.solace.cloud_solace_broker_std";
            proxy_cache_valid any 5s;
            proxy_pass_request_body off;
            proxy_set_body scrapeURI=https%3A%2F%2Fmr-0yg8yf443f2.messaging.solace.cloud%3A943&username=TmsIadIltisgateway-admin&password=o9l2bbbbbccccaaaa;
            proxy_set_header Content-Type "application/x-www-form-urlencoded";
        }
        
        .... a location for each broker
    }
}

```

example prometheus config

```
  - targets: [solace-cloud-monitoring.apps.trs01p.sbb-aws.net:443]
    labels:
      __metrics_path__: "/tms/iad/iltisgateway/t-ltta/det"
      __scheme__: "https"
      exporter_url: "https://solace-cloud-monitoring.apps.trs01p.sbb-aws.net:443/tms/iad/iltisgateway/t-ltta/det"
      app: "monitoring.solace-cloud.monalesy"
      group: "Solace"
      instance: "tms/iad/iltisgateway/t-ltta"
      job: "solace_details"
      solace_type: "cloud"
      stage: "test"

  - targets: [solace-cloud-monitoring.apps.trs01p.sbb-aws.net:443]
    labels:
      __metrics_path__: "/tms/iad/iltisgateway/t-ltta/stats"
      __scheme__: "https"
      exporter_url: "https://solace-cloud-monitoring.apps.trs01p.sbb-aws.net:443/tms/iad/iltisgateway/t-ltta/stats"
      app: "monitoring.solace-cloud.monalesy"
      group: "Solace"
      instance: "tms/iad/iltisgateway/t-ltta"
      job: "solace_statistics"
      solace_type: "cloud"
      stage: "test"
```
