### ISSUE TITLE
Discussion: Howto implement exclusion filters for (queue) metrics

### ISSUE THREAD

**Issue by andreas-habel** [solacecommunity/solace-prometheus-exporter#59]
Hi Solace Community,

we're using the Prometheus exporter very successfully, but since we get more and more assets on our brokers we see timeouts and gaps in our metrics. Error messages like `Can't scrape QueueDetailsSemp1 ..... context deadline exceeded`  show up in the logs.
One reason surely is, that on one broker we do have +4500 Queues, which is obviously too much and causes timeouts. Also additionally we're afraid if gathering those metrics every minute may harm the broker.

In theory, it would be fine if we could filter the gathered queue metrics, because roughly 50% of them are not as time critical - we could export those metrics less often. 
However, the exporter does not support blacklisting queue names with a `!` or similar. There just is no option to do something like this:
`http://your-exporter:9628/solace?m.QueueStats=myVpn|!ARBON`
And using whitelisting instead would require us to add / change the query constantly.

So basically a feature request would be to be able to exclude metrics gathering for queues that start with a specific name/string.

Of course this is not even problem of the exporter, since it just forwards the filter to the the SEMP API
```xml
<rpc><show><queue><name>" + itemFilter + "</name><vpn-name>" + vpnFilter + "</vpn-name><stats/><count/><num-elements>100</num-elements></queue></show></rpc>
```

Because I currently see no good solution how this could be implemented I wanted to create this post for a potential discussion.

How did Solace solve that with Datadog and Insights?
Do you have similar challenges or Issues?

**Comment by andreas-habel** [comment]
One Idea I came up with does not solve the "to much queue metrics" issue, but at least could prevent overload on the broker by introducing a rate limiting on outgoing SEMP requests. 
One library that would potentially help here could be https://pkg.go.dev/golang.org/x/time/rate#Limiter.Wait
This of course would slow down overall scraping performance and requires increased timeouts on prometheus.

Digging deeper into potential request limits I found 2 different numbers which are bit confusing

1.) SEMP v1 Polling Frequency Guidelines
> The event broker supports a maximum SEMP v1 polling rate of ten requests per second.
https://docs.solace.com/Admin/SEMP/Using-Legacy-SEMP.htm#SEMP_v1_Polling_Frequency_Guidelines

2.) SEMP v1 Request Over HTTP Service
> The event broker supports a maximum of 500 concurrent SEMP v1 requests over HTTP sessions.
https://docs.solace.com/Admin/SEMP/Using-Legacy-SEMP.htm#SEMP_v1_Request_Over_HTTP_Service

Does that mean, there could be up to 500 simultaneous requests open, but not more then 10 newly opened per second?

**Comment by GreenRover** [comment]
The sempv1 api only returns 100 items at once. And paging is required to get all results. But paging at solace is implemented with result pointer not with page numbers, There for parallelize the paging results is not as easy as expected.

But you can use Prometheus to parallelize.
Just scrape  
- myVpn|*a
- myVpn|*b
- myVpn|*c
- myVpn|*d
- ....

PS asked solace to check to may be provide a better filter possibility for sempv1 or semp2 at this point.

**Comment by GreenRover** [comment]
Would the sempv2 filter may be fit your needs?
https://docs.solace.com/Admin/SEMP/SEMP-Features.htm#Filtering

**Comment by andreas-habel** [comment]
> Would the sempv2 filter may be fit your needs? https://docs.solace.com/Admin/SEMP/SEMP-Features.htm#Filtering

Yes, sure. I think the `SEMP/v2/monitor/msgVpns/{vpn}/queues` endpoint with it's `where` and `select` options would be way more flexible then the legacy SEMP V1 API.
Ist there any reason why the exporter still uses SEMPv1 besided that just no one changed it? ;)
Is there more overhead on the broker expected?

**Comment by GreenRover** [comment]
yes semp v2 was slower last time i reviewed. But i know solace improved in meanwhile.

Next question do you like to provide an endpoint using v2 or do you wait for me to do this (may be i will find the time this year)

**Comment by andreas-habel** [comment]
I would not complain if I can just grab a new exporter version with the new endpoint, but of course we're willing to contribute as well.
Just to get on the same track - you're suggestion is to provide new datasources like `VpnStatsV2` and `QueueStatsV2` which allow for more advanced filtering. But they should still return the same metrics so that dashboards and alerts must not be changed. 
That also means, that using `QueueStats` and `QueueStatsV2` datasources in the same endpoint definition should be prevented.

```ini
[endpoint.new-sempv2]
VpnStatsV2=default|*
QueueStatsV2=default|!exclude/those/queues
```
This option would be the most flexible I guess and would allow slow transition for users. In theory this would even allow to define which metrics should be exported by extending the filtering options with the `select` parameter.

```ini
[endpoint.new-sempv2-with-select]
QueueStatsV2=default|!exclude/those/queues|bindRequestRate,bindSuccessCount
```
Other option would be to have a global "useSempV2" flag, that would automatically use SEMPv2 for every datasource where it is available

```go
func (e *Exporter) Collect(ch chan<- prometheus.Metric) {
...
case "QueueStats":
   if e.config.useSempV2 {
      up, err = e.semp.GetQueueStatsSemp2(ch, dataSource.VpnFilter, dataSource.ItemFilter)
   } else {
      up, err = e.semp.GetQueueStatsSemp1(ch, dataSource.VpnFilter, dataSource.ItemFilter)
   }
```

**Comment by GreenRover** [comment]
I like the new v2 datasources more. Because i fear that sempv2 and sempv1 powered endpoints will provide totally the same metrics.

The idea with parametrize able select options is very good. But i here we should be able to enter metric name and map it in exporter back to the sempv2 field name.

To coordinate, the first of us having time to work on this issue just post here to avoid doubled work

**Comment by GreenRover** [comment]
I started work here: https://github.com/solacecommunity/solace-prometheus-exporter/pull/60

**Comment by GreenRover** [comment]
I implemented queue stats with v2 api. 
Please test if it fits the requirements / improves the situation:
https://hub.docker.com/r/solacecommunity/solace-prometheus-exporter/tags?page=1&name=testing

**Comment by JanGrosse** [comment]
Hi @GreenRover,

thanks for implementing this so fast 💯 

I tried to test it today, but sadly failed. Pretty sure I am doing something wrong on my end.
I updated the image, added the environment variable for `SOLACE_DEFAULT_VPN` and updated my configmap.
It now contains the following new endpoint:

```
[endpoint.solace-esb-sempv2]
QueueStatsV2=pksolocp01|queueName%21%3Desb%2Fq%2Fkfl%2Fsib%2Fdata%2Fin*|solace_queue_msg_shutdown_discarded,solace_queue_msg_max_redelivered_discarded
```
(I also changed and tried with / without URL encoding)

But this sends the pod into a CrashLoopBackOff with the following error

```
ts=2023-12-12T11:59:52.240Z caller=solace_prometheus_exporter.go:77 level=error msg="exactly one \"|\" expected at endpoint \"solace-esb-sempv2\". Found key \"QueueStatsV2\" value \"pksolocp01|queueName%21%3Desb%2Fq%2Fkfl%2Fsib%2Fdata%2Fin*|solace_queue_msg_shutdown_discarded,solace_queue_msg_max_redelivered_discarded\". Expecected: VPN wildcard | item wildcard"
```

**Comment by GreenRover** [comment]
I fixed this issue now. Please test again.

I performed a performance test as well:

1. I created 9000 queues named "not/interesting/{i}"
2. As well as 90 queues named "important/queue/{i}"

Started the exported like this:
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: solace-exporter-config
data:
  solace_prometheus_exporter.ini: |
    [solace]
    listenAddr = 0.0.0.0:1920
    enableTLS = false
    scrapeUri = https://mr-connection-j6em7yuyi7k.messaging.solace.cloud:943
    username = monitoring
    password = monitoring
    defaultVpn = AaaBbbCcc
    timeout = 60s
    sslVerify = false

    [endpoint.solace-v1-test]
    QueueStats = AaaBbbCcc|*

    [endpoint.solace-v2-test]
    QueueStatsV2 = AaaBbbCcc|queueName!=not/interesting*|solace_queue_msg_shutdown_discarded,solace_queue_msg_max_redelivered_discarded
---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: solace-exporter
  labels:
    app: solace-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solace-exporter
  template:
    metadata:
      labels:
        app: solace-exporter
      annotations:
        collectord.io/logs-output: devnull
    spec:
      volumes:
        - name: solace-exporter-config-volume
          configMap:
            name: solace-exporter-config
            defaultMode: 420
      containers:
        - resources:
            limits:
              cpu: 300m
              memory: 800M
            requests:
              cpu: 150m
              memory: 500M
          readinessProbe:
            httpGet:
              path: /metrics
              port: 1920
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 7
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 2
          terminationMessagePath: /dev/termination-log
          name: solace-exporter
          command:
            - /solace_prometheus_exporter
            - '--config-file=/etc/solace/solace_prometheus_exporter.ini'
          livenessProbe:
            httpGet:
              path: /metrics
              port: 1920
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 7
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          env:
            - name: SOLACE_LISTEN_ADDR
              value: '0.0.0.0:1920'
            - name: SOLACE_LISTEN_TLS
              value: 'false'
            - name: TZ
              value: UTC
          ports:
            - containerPort: 1920
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: solace-exporter-config-volume
              readOnly: true
              mountPath: /etc/solace
          image: 'docker.bin.sbb.ch/solacecommunity/solace-prometheus-exporter:latest'
      restartPolicy: Always

---

kind: Service
apiVersion: v1
metadata:
  name: solace-exporter
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: 1920-tcp
      protocol: TCP
      port: 1920
      targetPort: 1920
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: solace-exporter

---

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: solace-exporter
spec:
  to:
    kind: Service
    name: solace-exporter
  tls:
    termination: edge
  host: solace-exporter.apps.trs01t.sbb-aws-test.net
  port:
    targetPort: 1920-tcp
```

### Result:

Query "solace-v2-test" took 13.84 sec
Query "solace-v1-test" took  9.99 sec

What your need to know about solace semp v2.
There "where" works not as expected. Compared to SQL it compares more like a "having".
Meaning it only filters what is returned to the client, but here for solace exporter needs walk throug all the pages in my case 9090/100 == 91 SempV2 and/or SempV1 query to get the result set.
