### ISSUE TITLE
Discussion: RetEx Dynatrace with ideas

### ISSUE THREAD

**Issue by osd42** [solacecommunity/solace-prometheus-exporter#64]
Hello Solace Community !
First, thank you for the exporter ! We are currently deploying it at a large and hybrid scale. I wanted to give a return of experience and perhaps inspire some ideas.

We developed a custom Dynatrace (extension v2) to ingest metrics from **solace-prometheus-exporter (SPE)**. 
Per stack we deploy a SPE container on the Dynatrace ActiveGate(s) (or directly using the OneAgent), and then the solace extension queries SPE ! 

Here is my **Dynatrace RetEx** with SPE: 
- SPE metrics:
  + we had to remove labels (prometheus terminology) or dimensions (dynatrace terminology) with **cardinality issues** : client_name in client_ and connection_ metrics. Dynatrace refused metrics after 3 days and 38000 client_name were referenced, Prometheus (was tested in parallel) survived less than a week from 8 to 64 GB of RAM with a lot of long restarts and missed metrics ! Perhaps a more detailed documentation with modulars endpoints for each use-case could help to choose metrics wisely (we have a lot of hybrid solace clusters on-prem/multi cloud). In my case I asked the company Solace expert to check my "hacks" on SPE modular endpoints because my strategy was to get all metrics from all nodes using multiple modular endpoints per node (and to avoid metrics duplicates conflicts). Nevertheless, I'd like to know how do you manage client_name cardinality in your DB ? Do you drop some labels or keep a week retention only ? Or perhaps you do never collect client and connection stats for this same reason ? I do use "client_username" as client id, and it seems to be the name of the SSL certificate of the client.
  + I faced issues with metrics duplicated names from different sources (_ClientMessageSpoolStats=*|* => cannot be together with clientStats because client_low_subscriber has the name description (inconsistent label) ; ; ConfigSyncRouter=*|* => same metrics as ConfigSyncVPN=*|* ;; ;ClientSlowSubscriber=*|* => removed, slow subscriber is already present in "Client"_)
  + difficulty to distinguish _publishers_ and _consumers_ in my dashboards (as I am new on Solace monitoring and concepts): the words do not exist in metric Description, but our (human) clients mostly talk about "topics, publish/subscribe" and I answer "Clients and Queues, Topic Endpoints".
  + observability issues with SPE metrics for tracing correlation: **I'll post a dedicated discussion issue for this !**
- SPE configuration
  + it seems the exporter is made only for Prometheus. So I needed to add the scrape target context (solace node + cluster name) on each metric at dynatrace extension level. Perhaps my usecase is rare, but it we are several not to use Prometheus scrape config to query SPE it could be an idea to add target labels arguments as URL variables (like "&target_label_node=solace0&target_label_cluster=cluster1") to generate any needed context label on the fly.
- Solace monitoring considerations:
  + our architects tend to make the notion of Message VPN disappear, they want to use only the default VPN in the future. I have the _intuition_ it is a bad idea for monitoring as SPE "vpn_name" is the common key between metrics.  (and a bad idea to have a unique name of vpn for tons of hybrid Solace clusters in production). Do you have an opinion or advice or a stunning argument ?
- Dynatrace limitations:
  + all scrapes (on all nodes) are sent at the same moment, so the impact on nodes and cluster is potentially huge (Prometheus puts seconds between each scrape target)
  + Dynatrace adds a label "endpoint_activation" on each metric with the whole URL query to SPE, so we choose not to send credentials via the arguments of a GET request
  + Dynatrace does not appreciate `solace_up{error=""}` and the dimension "error" is not created, I don't know how to generate errors. But in the same time I fear another cardinality problem if errors are spamming. How do we use solace_up error field ? In my case Dynatrace has its own mecanism to detect an extension failed a prometheus scrape so I could remove it.

Thank your for reading !

**Comment by GreenRover** [comment]
@osd42 Let me first introduce my environment bevor digging into your questions.

I am a solace customer operating multiple solace clouds with a total of > 200 broker as well as > 50 on prem broker. 
All are scraped with a single Prometheus instance. Without any problems. Prometheus is keeping only 3 days of metrics but the long term metrics are stored by thanos (in S3) for 2 years.
This gives me the benefit of:
- prometheus is mostly used for scraping metrics
- prometheus is as well evaluating alerting rules
- thanos is providing querys for grafana boards or other manual analytics

For prometheus are labels very important to make metrics join able and compareable.
The exporter is currently totally focusing on Prometheus.

To your questions:
- we had to remove labels:  no we keep all labels to able to join metrics. But when develop the exporter we focus on keeping the number of labels small because we are aware of the cost of to much labels. 
-- For the clients there you need to know that a singe client_username can connect multiple times. This is why we have the additional client_name to have a it clearly identifiable. Because the combination of client_username and client_name is unique per msg vpn & broker.
- duplicated `client_low_subscriber` this is a very good point. Thanks for pointing out. I personally use "ClientMessageSpoolStats" only temporary for debug purpose (because it is an expensive query, that may harm broker performance) there for i not jet run into this problem. I created a dedicated issue: https://github.com/solacecommunity/solace-prometheus-exporter/issues/65
- difficulty to distinguish publishers and consumers in my dashboards: Sorry i dont know how to help / what to answer here. What try you exactly to achive?
- Tracing is not jet supported. Because i am not interested in this feature. I would use some more import how / what is used / required.
- So I needed to add the scrape target context. This problem is solved in prometheus by target labels.
Example:
    ```
    - job_name: 'solace-std'
      scrape_interval: 15s
      metrics_path: /solace-std
      static_configs:
        - targets:
          - https://USER:PASSWORD@first-broker:943
          - https://USER:PASSWORD@second-broker:943
          - https://USER:PASSWORD@third-broker:943
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: solace-exporter:9628
    ```
     Here you get the labels:
    - instance = hostname of broker
    
    OR
    
    ```
    - job_name: 'solace-std'
      scrape_interval: 15s
      metrics_path: /solace-std
      static_configs:
        - targets:
          - https://USER:PASSWORD@first-broker:943
          labels:
           broker_name: your-name-of-first-broker
        - targets:
          - https://USER:PASSWORD@second-broker:943
          labels:
           broker_name: your-name-of-second-broker
        - targets:
          - https://USER:PASSWORD@third-broker:943
          labels:
           broker_name: your-name-of-third-broker
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: solace-exporter:9628
    ```
     Here you get the labels:
    - instance = hostname of broker
    - broker_name = your name of the broker

I dont know DynaTrace. But if you provide informations how you provide the SPE endpoints to DynaTrace, may be i can find a similar solution here.

- our architects tend to make the notion of Message VPN disappear: With prometheus i would just drop the label in this case.
Example:
    ```
    - job_name: 'solace-std'
      scrape_interval: 15s
      metrics_path: /solace-std
      static_configs:
        - targets:
          - https://USER:PASSWORD@first-broker:943
          - https://USER:PASSWORD@second-broker:943
          - https://USER:PASSWORD@third-broker:943
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: solace-exporter:9628
        - source_labels: vpn_name
          action: drop
    ```
- Dynatrace adds a label "endpoint_activation": Please have a look at: https://github.com/solacecommunity/solace-prometheus-exporter/tree/master/examples/nginx_reverse_proxy. This is how i solve this problem with prometheus.

- Dynatrace does not appreciate `solace_up{error=""}` Because prometheus provides the "job" label automatically this metric is unique out of the box. Important here is to know the difference between `up`  and `solace_up`
-- `up` metric is what Dynatrace will provide as well. This is when the exporter is not reachable.
-- `solace_up` provide information when the exporter is healthy but the broker can not be scraped.

**Comment by osd42** [comment]
Thank your for your answer @GreenRover !

About the target labels for Dynatrace, this is my workaround in Dynatrace extension v2, this will add 2 labels on each metric at configuration level.

```yaml
vars:
  - id: nodename
    displayName: Name of the Solace node
    type: text
  - id: clustername
    displayName: Name of the Solace cluster
    type: text
prometheus:
  - group: Solace Metrics
    interval:
      minutes: 1
    dimensions:
      - key: node
        value: var:nodename
      - key: cluster
        value: var:clustername
```

This is the configuration result in a Dynatrace extension "monitoring configuration" (you will notice familiar names) : 
![image](https://github.com/solacecommunity/solace-prometheus-exporter/assets/49947845/ff44cee7-c2e6-45e1-ba20-0ab16737cedd)
