### ISSUE TITLE
[Feature]: SempV1 exclusive queue filter

### ISSUE THREAD

**Issue by osd42** [solacecommunity/solace-prometheus-exporter#72]
### Feature Description

Hello
Is it possible to add an exclude filter on the SEMPv1 Queue* scopes ? (QueueStats, QueueRates, QueueDetails)

Best regards
Charles

### Use Case

We would like to filter out MQTT queues from our metric ingestion (because of cardinality issues in our backend, and due to the ephemeral nature of the mqtt queue name: 2000mqtt queues per day).
The queue filter feature exists in QueueStats2. The SEMPv2 QueueStats2 allows to filter out any queue pattern but it requires a specific configuration for each VPN (this is great for Solace Cloud which seems to only have 1 VPN, but not for most of my cases).

### Proposed Solution

Perhaps we could add new parameters to select and ignore matching queue_name in the SEMPv1 exposed results : 
`?queue_filter_inclusive=*&queue_filter_exclusive=#mqtt*`

**Comment by GreenRover** [comment]
You can do this with prometheus. Please check following links:

https://prometheus.io/docs/prometheus/latest/configuration/configuration/#metric_relabel_configs
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config

Example:
```
scrape_configs:
  - job_name: 'solace-exporter-01'
    static_configs:
      - targets: [ 'localhost:9100' ]
    metric_relabel_configs:
    - source_labels: [queue_name]
      action: drop
      regex: '#mqtt/.*'
```
