### ISSUE TITLE
[Bug]: Old gauges remain open

### ISSUE THREAD

**Issue by pascalre** [solacecommunity/solace-prometheus-exporter#84]
### Bug Description

We have encountered an issue where old gauges remain open even after the metrics have changed. This behavior has been observed with the following metrics:

- `solace_up`
- `solace_client_slow_subscriber`

It seems that there are potentially more affected metrics. These metrics are gauges that can both increase and decrease. When the exporter modifies the labels for these metrics, new gauges are created upon value changes.

**Description for metric solace_up:**
When the Solace broker is functioning correctly, the metric `solace_up` appears as follows:
```
solace_up{error=""} 1
```

However, when an error occurs, it changes to:
```
solace_up{error=""} 1
solace_up{error="Post "https://***": read tcp ***->***: read: connection reset by peer"} 0
```

As you can see, the old gauge without the error description remains, and a new one is created. When the error is resolved and the Solace broker is back to normal operation, the error-related metric remains and is not removed.

See the image below:
![Image](https://github.com/user-attachments/assets/337fb28f-8461-4bf1-bf80-59d1504a3ed1)

**Description for metric solace_client_slow_subscriber:**
Once a gauge was registered for a slow subscriber, the gauge remains open (event if the slow subscriber is not present anymore).

**Additional Context:**
This issue may lead to confusion when monitoring the metrics, as it can make it difficult to ascertain the current state of the Solace broker. Gauges will be cleared on pod restart.

Exporter version: 1.8.2

### Expected Behavior

The exporter should clean up old gauges when the metrics change, ensuring that only relevant and current metrics are displayed.

### Steps to Reproduce

1. Start the Solace broker and observe the `solace_up` metric.
2. Introduce an error and observe the creation of a new gauge with the error code.
3. Resolve the error and check if the old gauge without the error code is still present.

**Comment by GreenRover** [comment]
Everything works as expected:

![Image](https://github.com/user-attachments/assets/6a244f27-741e-4594-9516-2dfae1378823)

You should be aware of that a changed label like the "error" label means for Prometheus a new metric.
But disappeared metrics should be remove after 5min:
https://prometheus.io/docs/prometheus/latest/querying/basics/#staleness

**Comment by dwray** [comment]
It looks like there is a minor error in exporter.collect.go which means ch <- e.semp.NewMetric(semp.MetricDesc["Global"]["up"], prometheus.GaugeValue, 1, "") is always set, even if there is an error.

<snip>
		if up < 1 {
			if err != nil {
				ch <- e.semp.NewMetric(semp.MetricDesc["Global"]["up"], prometheus.GaugeValue, 0, err.Error())
			} else {
				ch <- e.semp.NewMetric(semp.MetricDesc["Global"]["up"], prometheus.GaugeValue, 0, "Unknown")
			}
			break
		}
	}

	ch <- e.semp.NewMetric(semp.MetricDesc["Global"]["up"], prometheus.GaugeValue, 1, "")

Changing it to be like this should resolve that problem:

<snip>
		if up < 1 {
			if err != nil {
				ch <- e.semp.NewMetric(semp.MetricDesc["Global"]["up"], prometheus.GaugeValue, 0, err.Error())
			} else {
				ch <- e.semp.NewMetric(semp.MetricDesc["Global"]["up"], prometheus.GaugeValue, 0, "Unknown")
			}
			break
		}

		ch <- e.semp.NewMetric(semp.MetricDesc["Global"]["up"], prometheus.GaugeValue, 1, "")
	}

**Comment by pascalre** [comment]
@dwray this example works perfectly fine for the solace_up metric. I opened #91 for that.

**Comment by pascalre** [comment]
@GreenRover, the issue with the solace_up metric is still unresolved despite your [commit](https://github.com/solacecommunity/solace-prometheus-exporter/commit/224ccfa9cda2269ee14e52215aa0d1b5a875cd33).

I have another example illustrating this problem: when creating a queue named `exporter-test`, the exporter automatically detects the corresponding metric. However, after deleting the queue, the gauge remains active. Ideally, the gauge should be deregistered from the registry upon deletion, which would remove the metric entirely.

![Image](https://github.com/user-attachments/assets/3cf62d18-8edc-4998-8816-9449f5866cc5)

![Image](https://github.com/user-attachments/assets/e09b25fa-966a-4101-b5dc-ff92330a1eef)

All gauges in this project seem to be affected by this problem.

Could you please reopen this issue? Thank you!

**Comment by GreenRover** [comment]
This is not a problem of the exporter. 
In prometheus there is no "delete" metric.
It simply needs to disappear from a exporter url. 

And it works as expected:
![Image](https://github.com/user-attachments/assets/7fd87dcd-884b-4859-9bb1-62692727d2db)

Please consult a prometheus export fixing up your installation.

**Comment by GreenRover** [comment]
Screenshot from prometheus 2.55.1  (the last was from thanos)

![Image](https://github.com/user-attachments/assets/dee2e16c-f013-4a8f-9ccf-cc72e6367c3b)


Here my simplified prometheus config, including all defaults:

```yaml
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  evaluation_interval: 2m
  external_labels:
    prometheus: monalesy-monitoring-solace-prod
    prometheus_replica: monalesy-prometheus-main-0
alerting:
  alert_relabel_configs:
  - separator: ;
    regex: prometheus_replica
    replacement: $1
    action: labeldrop
  alertmanagers:
  - follow_redirects: true
    enable_http2: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets:
      - monalesy-alertpreprocessor-main-0.xxxx:8487
      - monalesy-alertpreprocessor-main-1.xxxx:8487
scrape_configs:
- job_name: test
  honor_labels: true
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 1m
  scrape_timeout: 50s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: http
  enable_compression: true
  tls_config:
    ca_file: /etc/prometheus_secret/ca.crt
    cert_file: /etc/prometheus_secret/prometheus.crt
    key_file: /etc/prometheus_secret/prometheus.key
    insecure_skip_verify: true
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - xxxxxxxxxxxxxt:443
    labels:
      __metrics_path__: /xxxx/det
      __scheme__: https
      alertStage: DEV
      app: monitoring.solace-cloud.monalesy
      exporter_url: https://xxxxxxxxxxxxx:443/xxxx/det
      group: Solace
      instance: tms/solacetest/heiko/d-halonapp
      job: solace_details
      solace_type: cloud
      stage: dev
```
